In [144]:
import importlib, sys, subprocess
try:
    import pandas as pd
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"])
    importlib.invalidate_caches()
    import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [145]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [146]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [147]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [148]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [149]:
df['Review Rating']= df.groupby(df['Category'])['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [150]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [151]:
df.columns = [
    "_".join(map(str, col)).strip().lower().replace(" ", "_")
    if isinstance(col, tuple)
    else str(col).strip().lower().replace(" ", "_")
    for col in df.columns
]

df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount_usd'})

In [152]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  promo_code_used         3900 non-null   str
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   str
 17  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [153]:
labels = {'young_adult': 'Young Adult', 'adult': 'Adult', 'middle_aged':'Middle Aged', 'senior': 'Senior'}
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [154]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  middle_aged
1   19  young_adult
2   50  middle_aged
3   21  young_adult
4   45  middle_aged
5   46  middle_aged
6   63       senior
7   27  young_adult
8   26  young_adult
9   57  middle_aged

In [155]:
#Map purchase frequency to numeric values
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90,
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [156]:
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [157]:
(df['discount_applied'] == df['promo_code_used']).all() #checking redundancy

np.True_

In [158]:
df.drop('promo_code_used' , axis=1, inplace=True)

In [159]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount_usd      3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), str(12)
memory usage: 552.6 KB

In [160]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\charv\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\charv\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\charv\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [161]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\charv\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [162]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = 'postgres'
password = quote_plus('Devanit@1976')
database = 'Customer_Behavior'
host = 'localhost'
port = '5432'

engine = create_engine(
    f'postgresql://{username}:{password}@{host}:{port}/{database}'
)

table_name = 'customer'

df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"DataFrame successfully written to the '{table_name}' table in the '{database}' database.")

DataFrame successfully written to the 'customer' table in the 'Customer_Behavior' database.

In [163]:
df[['purchase_frequency_days',
    'previous_purchases',
    'purchase_amount_usd']].describe()

       purchase_frequency_days  previous_purchases  purchase_amount_usd
count              3900.000000         3900.000000          3900.000000
mean                 89.133077           25.351538            59.764359
std                 119.037566           14.447125            23.685392
min                   7.000000            1.000000            20.000000
25%                  14.000000           13.000000            39.000000
50%                  30.000000           25.000000            60.000000
75%                  90.000000           38.000000            81.000000
max                 365.000000           50.000000           100.000000

In [164]:
features = df[
    [
        'purchase_frequency_days',
        'previous_purchases',
        'purchase_amount_usd'
    ]
]

In [165]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(features)

In [166]:
from sklearn.cluster import KMeans

inertia = []

for k in range(1,11):

    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    km.fit(X)

    inertia.append(km.inertia_)

In [167]:
kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df['cluster'] = kmeans.fit_predict(X)

In [168]:
kmeans_profile = (
    df.groupby('cluster')
    .agg({
        'purchase_amount_usd':'mean',
        'previous_purchases':'mean',
        'purchase_frequency_days':'mean'
    })
)

print(kmeans_profile)

         purchase_amount_usd  previous_purchases  purchase_frequency_days
cluster
0                  36.160635           31.335393                40.466019
1                  79.947525           36.839604                42.797030
2                  60.173077           24.561189               365.000000
3                  64.932489           10.220253                41.996624

In [169]:
cluster_count = df['cluster'].value_counts().sort_index()

print("\nK-Means Cluster Distribution")
print(cluster_count)

K-Means Cluster Distribution
cluster
0    1133
1    1010
2     572
3    1185
Name: count, dtype: int64

In [170]:
cluster_revenue = (
    df.groupby('cluster')['purchase_amount_usd']
      .sum()
      .sort_values(ascending=False)
)

print("\nRevenue by K-Means Cluster")
print(cluster_revenue)

Revenue by K-Means Cluster
cluster
1    80747
3    76945
0    40970
2    34419
Name: purchase_amount_usd, dtype: int64

In [171]:

cluster_profile = (
    df.groupby('cluster')
      .agg({
          'purchase_amount_usd':'mean',
          'previous_purchases':'mean',
          'purchase_frequency_days':'mean'
      })
      .round(2)
)

print("\nK-Means Cluster Profile")
print(cluster_profile)

K-Means Cluster Profile
         purchase_amount_usd  previous_purchases  purchase_frequency_days
cluster
0                      36.16               31.34                    40.47
1                      79.95               36.84                    42.80
2                      60.17               24.56                   365.00
3                      64.93               10.22                    42.00

In [172]:
cluster_revenue_share = (
    df.groupby('cluster')['purchase_amount_usd']
      .sum()
      .div(df['purchase_amount_usd'].sum())
      .mul(100)
      .round(2)
)

print("\nK-Means Revenue Share (%)")
print(cluster_revenue_share)

K-Means Revenue Share (%)
cluster
0    17.58
1    34.64
2    14.77
3    33.01
Name: purchase_amount_usd, dtype: float64

In [173]:
cluster_subscription = pd.crosstab(
    df['cluster'],
    df['subscription_status'],
    margins=True
)

print("\nK-Means vs Subscription")
print(cluster_subscription)

K-Means vs Subscription
subscription_status    No   Yes   All
cluster
0                     817   316  1133
1                     729   281  1010
2                     412   160   572
3                     889   296  1185
All                  2847  1053  3900

In [174]:
cluster_discount = pd.crosstab(
    df['cluster'],
    df['discount_applied'],
    normalize='index'
).round(3) * 100

print("\nK-Means Discount Usage (%)")
print(cluster_discount)

K-Means Discount Usage (%)
discount_applied    No   Yes
cluster
0                 56.2  43.8
1                 56.3  43.7
2                 58.4  41.6
3                 57.6  42.4

In [175]:
cluster_rating = (
    df.groupby('cluster')['review_rating']
      .mean()
      .round(2)
)

print("\nAverage Review Rating by Cluster")
print(cluster_rating)

Average Review Rating by Cluster
cluster
0    3.72
1    3.80
2    3.76
3    3.74
Name: review_rating, dtype: float64

In [176]:
from sklearn.metrics import silhouette_score

score = silhouette_score(X, df['cluster'])

print("Silhouette Score:", round(score,3))

Silhouette Score: 0.358

In [177]:
df = df.drop(columns=[
    'F_score',
    'M_score',
    'FM_segment'
], errors='ignore')

In [179]:
cluster_names = {
    0: 'Budget Loyal Customers',
    1: 'High-Value Loyal Customers',
    2: 'Seasonal Customers',
    3: 'Occasional Premium Buyers'
}

df['cluster_name'] = df['cluster'].map(cluster_names)

In [180]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,...,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days,cluster,cluster_name
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Express,Yes,14,Venmo,Fortnightly,middle_aged,14,3,Occasional Premium Buyers
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Express,Yes,2,Cash,Fortnightly,young_adult,14,3,Occasional Premium Buyers
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle_aged,7,3,Occasional Premium Buyers
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,Next Day Air,Yes,49,PayPal,Weekly,young_adult,7,1,High-Value Loyal Customers
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Free Shipping,Yes,31,PayPal,Annually,middle_aged,365,2,Seasonal Customers

In [182]:
df[['customer_id','cluster','cluster_name']].to_sql(
    'temp_clusters',
    engine,
    if_exists='replace',
    index=False
)

900